type Option {
  id: ID!
  text: String!
  score: Int!
  question: Question!
  answers: [Answer]
}

type Question {
  id: ID!
}

type Answer {
  id: ID!
}

type Query {
  getOption(id: ID!): Option
}

type Mutation {
  addSurvey(title: String!): Survey
}
