type Answer {
  id: ID!
  user: User!
  survey: Survey!
  question: Question!
  option: Option!
  createdAt: String!
}

type User {
  id: ID!
}

type Survey {
  id: ID!
}

type Question {
  id: ID!
}

type Option {
  id: ID!
}

type Query {
  getAnswer(id: ID!): Answer
}

type Mutation {
  addSurvey(title: String!): Survey
}
