type Survey {
  id: ID!
  title: String!
  user: User!
  questions: [Question]
  answers: [Answer]
}

type User {
  id: ID!
  email: String!
}

type Question {
  id: ID!
  text: String!
  survey: Survey!
}

type Answer {
  id: ID!
}

type Query {
  getSurvey(id: ID!): Survey
}

type Mutation {
  addSurvey(title: String!): Survey
}
